#!/usr/bin/env perl

=head1 NAME

libbi - frontend to LibBi functionality.

=head1 SYNOPSIS

    libbi I<command> I<options...>

    libbi @I<options_file>
    libbi I<command> @I<options_file>

=head1 METHODS

=over 4

=cut

BEGIN {
    use FindBin qw($Bin);
    use File::Spec;

    unshift(@INC, File::Spec->catfile($Bin, '..', 'lib'));
}

use warnings;
use strict;

use Getopt::ArgvFile;

use Bi::FrontEnd;


my $frontend = new Bi::FrontEnd;
$frontend->do;

=back

=head1 AUTHOR

Lawrence Murray <lawrence.murray@csiro.au>


